name: Release PR Tagger

on:
  # trigger on pull-request merged to main branch
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # check the following items before procedding:
    # 1. the PR has been merged to branch `main`
    # 2. the PR title starts with string `Release`
    if: "{{ github.event_name == 'pull_request' && github.payload.pull_request.merged && github.payload.pull_request.base.ref == 'main' && (github.payload.pull_request.title | startswith 'Release') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # git tag the release.
      # The tag name is the string after `Release`, trimmed of whitespace
      - name: Tag Release
        id: tag_release
        run: |
          git tag -a ${{ github.payload.pull_request.title | startswith 'Release' | substringafter 'Release' | trim }} -m "Release ${{ github.payload.pull_request.title | startswith 'Release' | substringafter 'Release' | trim }}"
          git push origin ${{ github.payload.pull_request.title | startswith 'Release' | substringafter 'Release' | trim }}
          
